### ISSUE TITLE
Timeout getting receipt

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarmd#100]
**Describe the bug**
Might be related to #99, but receiving the following error during `POST /transactions`

`b'{"errors":{"errors":["transaction 08b4dcd10dc7ad3ada0cd314635a33f0b82cb17bcf0aeee80c411db8cc467b21: timeout waiting for receipt"]},"status":"FAIL"}`

**Comment by myhndl** [comment]
Have you observed this lately?

**Comment by mjkoo** [comment]
This is related to the txpool issue, have seen it correlated to when we see txpool growth, still unsure if we've resolved this with genesis change but it has been looking good so far

**Comment by myhndl** [comment]
Related: https://github.com/polyswarm/infrastructure/issues/45

Let's this ticket when we close the above.
