### ISSUE TITLE
Add status endpoint

### ISSUE THREAD

**Issue by eodgooch** [polyswarm/polyswarmd#104]
**Is your feature request related to a problem? Please describe.**
Polyswarmd process stops responding to requests. We should be proactive in culling bad processes in the docker swarm. This will ensure stability of the system without human intervention. Bad services die and are replaced with healthy services.

**Describe the solution you'd like**
Add an endpoint `status` that can be called by the docker swarm healthcheck component that yields a 200 response code if OK or 500 response code if not OK. The endpoint should perform some basic sanity check to ensure the process is behaving correctly. This could be verifying the websocket connection and/or some similar integration point.

**Describe alternatives you've considered**
Another option would be cull the process after subsequent failed requests but this will involve creating some in memory stateful data structure.

**Additional context**
This endpoint should be called from the docker compose service using the `healthcheck` [docker compose functionality](https://docs.docker.com/engine/reference/builder/#healthcheck)

**Comment by aarongooch** [comment]
The status EP should not be protected and execute a geth query to ensure connectivity to the chains exist. Consider using `syncing` ep as an example for a valid geth query.

**Comment by mjkoo** [comment]
clarification on "This could be verifying the websocket connection and/or some similar integration point."?

Is it enough to remove the API key requirement from `/syncing`, or do we have a specific list of things to check?

**Comment by aarongooch** [comment]
An explicit `status` EP without authentication that executes the same code as `syncing` EP is the desired solution. This will allow us to keep current API contract and handle a valid health check for the service

**Comment by myhndl** [comment]
1. I think we should canonicalize on `/status` for un-auth status checking.
2. Didn't `status` already exist? Does this amount to breaking compat?

**Comment by myhndl** [comment]
Applying BLOCKER label as this prevents proper alerting.

**Comment by mjkoo** [comment]
Deployed on stage and prod, closing
