### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by myhndl** [polyswarm/polyswarmd#123]
**Is your feature request related to a problem? Please describe.**
We've broken things in the past with API changes, this will be unacceptable post-Stable.

**Describe the solution you'd like**
* [ ] what we have now becomes API 1.0
* [ ] version should be explicit in all routes, e.g. `https://polyswarmd/1.0/bounties`
* [ ] future changes to API result in version bump
* [ ] backwards compatibility ensured to a to be determined extent

**Comment by scsich** [comment]
Who is this assigned to? @myhndl this is very close to actual release for such a change.

**Comment by myhndl** [comment]
Agreed, planned to and forgot to do this yesterday.

Will move off critical, furture breaking updates (1.1+) will introduce a version number.
