### ISSUE TITLE
Reject >1 Artifact / Bounty

### ISSUE THREAD

**Issue by myhndl** [polyswarm/polyswarmd#151]
**Is your feature request related to a problem? Please describe.**
We need ability to scale, multi-artifact bounties present scaling challenge.

**Describe the solution you'd like**
Reject a configurable number of artifacts / bounty, refuse to post it to chain. Set this to 1 for launch.

**Comment by scsich** [comment]
@Rizato can we close?

**Comment by Rizato** [comment]
Not yet. That change was in consumer. Polyswarmd needs to implement as well. I'll add this to my todo for today.
