### ISSUE TITLE
Connection pool is full, discarding connection: sidechain

### ISSUE THREAD

**Issue by ceseale** [polyswarm/polyswarmd#152]
**Describe the bug**
Potential Bug: Warnings saying `Connection pool is full, discarding connection: sidechain`. We might need to set a max pool size. Might be related to recent gunicorn changes.

**Additional context**
https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22tag_swarm_service%22%2C%22tag_poly_work%22%2C%22tag_container_name%22%5D&event=AAAAAWfEowXJtYf_PgAAAABBV2ZFb3dYZkNlM2xycV9Ja21tOA&from_ts=1545192277399&index=main&live=false&query=container_name%3Agamma_polyswarmd%2A+poly_work%3Astage+status%3Awarn&stream_sort=desc&to_ts=1545192277899

**Comment by mjkoo** [comment]
This seems to resolved itself satisfactorily, connection pool issue has not been observed since deploy, closing
