### ISSUE TITLE
Gamma review

### ISSUE THREAD

**Issue by myhndl** [polyswarm/polyswarmd#17]
1. [x] Maybe check if amount is greater than fees? (https://gitlab.polyswarm.io/polyswarm/polyswarmd/blob/f5e4ffb79667c175c62fe2ad5225261ec5cf825b/src/polyswarmd/relay.py)
1. [x] This should probably be dynamic. If we deploy something with too high of a cost, could break stuff: https://gitlab.polyswarm.io/polyswarm/polyswarmd/blob/f5e4ffb79667c175c62fe2ad5225261ec5cf825b/src/polyswarmd/eth.py#L29
1. [x]  In the future, should be using requests.Session for keep-alive and only constructing the base URL once in places like this: https://gitlab.polyswarm.io/polyswarm/polyswarmd/blob/f5e4ffb79667c175c62fe2ad5225261ec5cf825b/src/polyswarmd/artifacts.py#L26
1. [ ]  I kinda think we should use secure_filename on files before submitting them to IPFS. Don't want to rely on them handling dangerous paths correctly. That said, this may have an impact on scanners (if the malware behavior is somehow name-dependent); maybe there should be some metadata of the "original filename" associated somewhere? Would appreciate thoughts here: https://gitlab.polyswarm.io/polyswarm/polyswarmd/blob/f5e4ffb79667c175c62fe2ad5225261ec5cf825b/src/polyswarmd/artifacts.py#L59
1. [x]  Should the settle function check if a bounty is actually able to be settled currently? (https://gitlab.polyswarm.io/polyswarm/polyswarmd/blob/master/src/polyswarmd/bounties.py#L307)

**Comment by mjkoo** [comment]
1. Incurs cost of an RPC call for every withdrawal, I think its better to have a failing transaction
2. Not an easy way to do this afaict
3. Requests replaced with requests-futures, session mgmt done differently, consider this addressed
4. Disagree still
5. See 1, also this is a weaker case than 1 I think as we can conceivably prepare a settle tx prior to the block where it is transmitted

**Comment by myhndl** [comment]
Cc @supernothing as this was his review

**Comment by supernothing** [comment]
I don't have strong opinions on any except 4. It's a really dumb decision imo to be moving files around the entire system with their original names, and just invites disaster. While I brought up the specific potential problem of IPFS handling it incorrectly, there's any number of other places where it could be misused. It makes much more sense to canonicalize them and pass their original filename around as metadata, which I believe we should be working toward a system to do anyway.

Could you re-iterate your argument here @mjkoo ? The only argument I really see against it is potentially path-specific behavior, but this could be the case anyway given we aren't passing in a full path to the engines.
