### ISSUE TITLE
Signing of transactions from polyswarmd to microengine?

### ISSUE THREAD

**Issue by strazzere** [polyswarm/polyswarmd#27]
This might just simply be a misunderstanding in how this is meant to work, however I'm not following the trust model between polyswarmd and the microengine fully. It seems to be touched upon here as well;

https://github.com/polyswarm/microengine/#security-warning

Is there a proposed design on how a microengine is meant to assert that the transactions getting back to it are valid/from a trusted polyswarmd?

Was trying to mull over ideas, however it would seem that just adding signing doesn't inherently prove that the transaction is good, just that it was created by a specific account tied a polyswarmd instance.

**Comment by myhndl** [comment]
Sorry, it's late and I misread, this is being done now with `polyswarm-client` overhaul, e.g.: https://github.com/polyswarm/polyswarm-client/blob/7bab776e740bb817626836012869cee48fd500ee/src/polyswarmclient/__init__.py#L240

Related: https://github.com/polyswarm/polyswarm-client/issues/38
