### ISSUE TITLE
Using same account from multiple clients causes nonce errors

### ISSUE THREAD

**Issue by supernothing** [polyswarm/polyswarmd#28]
Currently, when running multiple ambassadors/microengines/arbiters using the same account causes nonce errors that results in one of the clients exiting.

Steps to reproduce:
1. Start up a dev environment with `orchestration`: `docker-compose -f dev.yml up`
2. Run two of the example ambassadors at the same time (also works with microengines as well though).

Expected result:
All bounties are submitted successfully.

Actual result:
`polyswarmd` will throw an error about the nonce being too low, and one of the ambassadors will exit with the following error:
```
Traceback (most recent call last):
  File "ambassador.py", line 206, in <module>
    bountyList = postBounties(numBountiesToPost, fileList)
  File "ambassador.py", line 168, in postBounties
    tempBounty.postBounty(BOUNTY_DURATION,nonce)
  File "ambassador.py", line 124, in postBounty
    if r.json()['status'] == 'OK':
KeyError: 'status'
```
A similar error occurs in the same case with the sample microengine.

I believe what's happening here is that both ambassadors were given the same nonce by `polyswarmd` when building their `postBounty` transaction. The ambassador here should probably be printing a more useful error, but `polyswarmd` should be returning a well-formed response that lets the ambassador/microengine/arbiter know to either resubmit with a different nonce or to stop trying.

**Comment by myhndl** [comment]
Medium-term, `polyswarmd` will not support multiple clients running with the same ETH address (or API key), closing as WONTFIX. 

Related issues being tracked in https://github.com/polyswarm/development-private/issues/28
