### ISSUE TITLE
Offers websocket transport

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarmd#36]
Currently polyswarmd's offers implementation opens websocket client connections to synchronize offer state, this may have made sense for one-polyswarmd-per-client but makes considerably less sense for hosted-polyswarmd

@ceseale thoughts?

**Comment by mjkoo** [comment]
This is not true anymore, but we should look into alternate transport options (currently all connections proxied through a polyswarmd instance, which is unnecessary). Closing.

**Comment by myhndl** [comment]
Is there a separate ticket for this design item you just mentioned?

**Comment by mjkoo** [comment]
https://github.com/polyswarm/development/issues/18
