### ISSUE TITLE
Auto-Generate API docs

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarmd#51]
Way easier to keep things in sync if we 1) Add docstrings 2) autogenerate docs e.g. for https://github.com/polyswarm/documentation/blob/master/_i18n/en/_docs/API-polyswarm.md

**Comment by mjkoo** [comment]
Potentially check out https://readme.io/swagger/

**Comment by mrtizmoatwork** [comment]
Need to use a tool like Sphinx to generate the content that is now on docs.polyswarm.io API page.
