### ISSUE TITLE
Reliability (in the TCP Sense)

### ISSUE THREAD

**Issue by myhndl** [polyswarm/polyswarmd#57]
**Is your feature request related to a problem? Please describe.**
`polyswarmd` is not reliable, meaning that it will not ensure to the best of its ability that transactions make it to / from the chain. Right now, `polyswarmd` operates a bit like UDP and needs to be a bit more like TCP.

Consider:
1. client sends txn with nonce 1
1. client sends txn with nonce 2, this is dropped en route
1. client sends txns with nonce 3-7

The chain will refuse txns with nonce 3+ after a timeout because nonce 2 failed to arrive. `polyswarmd` does not currently retry, but should.

**Describe the solution you'd like**
Monitor the chain for mined transactions. Retry txns that don't make it. Retry txns of subsequent nonce values for nonces that don't make it.

**Comment by myhndl** [comment]
In light of hosted `polyswarmd`, this is backwards and should be handled by `polyswarm-client`.

Are we good on this @mjkoo @Rizato or is more work needed? We re-try on nonce, obviously.

**Comment by mjkoo** [comment]
It retries a configurable amount of times for any tx failure, default being 5. Think we're good
