### ISSUE TITLE
Scalability (Nonce Coordination)

### ISSUE THREAD

**Issue by myhndl** [polyswarm/polyswarmd#58]
**Is your feature request related to a problem? Please describe.**
We currently cannot scale `polyswarmd`. More specifically, you cannot run multiple copies of `polyswarmd` at least in part because there's no way to pub/sub for nonce values.

**Describe the solution you'd like**
Develop a means for multiple instances of `polyswarmd` to agree on allocation of nonce values.

**Additional context**
Blocks on: https://github.com/polyswarm/polyswarmd/issues/57

**Comment by mjkoo** [comment]
In my mind this is a polyswarm-client problem and not a polyswarmd problem.

**Comment by myhndl** [comment]
In other words, multiple `polyswarm-client`s need to coordinate peer-to-peer on nonce values then dole them out to N instances of `polyswarmd`?

**Comment by mjkoo** [comment]
correct, polyswarmd doesn't/shouldn't keep state like that around, we've discussed adding in a default implementation of multi-process/network nonce sync into client, added an issue for that at https://github.com/polyswarm/polyswarm-client/issues/32

**Comment by myhndl** [comment]
Is there a reason to keep this ticket around @mjkoo ?

**Comment by mjkoo** [comment]
No
