### ISSUE TITLE
Handle geth restarts, gracefully or not

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/polyswarmd#65]
**Describe the bug**
When eth client is restarted, we lose all filter state which is being polled in the websocket handlers. There is possibly also more relevant state which is lost, need to look into this.

We should either A) handle gracefully, back off reconnect attempts then reset filters on success or B) handle by dying and waiting for our container to restart

B) seems doable in the short term to fix failures, A) should be investigated medium term to improve uptime outlook.

**To Reproduce**
1. `docker-compose -f dev.yml up`
2. Open websocket connection to `/events`
3. Kill geth container
4. See errors

**Expected behavior**
If we are unable to recover polyswarmd should exit with failure, else we should wait for geth to come back up, reinstall filters and continue delivering events

**Comment by mjkoo** [comment]
Closed by #66

**Comment by myhndl** [comment]
In light of the conversation in Slack today, I believe this wasn't actually the base issue, correct? Shall we re-close @mjkoo ?

**Comment by myhndl** [comment]
Bump on closing this @mjkoo

**Comment by mjkoo** [comment]
Yes this should be fixed, closing
