### ISSUE TITLE
Arbiter Staking Balance Always Reported as Zero

### ISSUE THREAD

**Issue by scsich** [polyswarm/polyswarmd#69]
**Describe the bug**
Arbiter staking balance is 0 after staking on a private sidechain.

**To Reproduce**
1. Run `arbiter stake` from Cuckoo repos
2. Get 200's back from stake and transaction submission
3. Check ` https://polyswarmd/balances/<eth addr>/staking/total`
4. See 0

**Expected behavior**
Amount staked comes back in 4.

**Comment by mjkoo** [comment]
Working with cuckoo on this in slack, our arbiters seem to be staking properly and balances are being reported:

```
curl -H "Authorization: XXXXXXXXXXXXXXXXXXXX" https://gamma-polyswarmd.prod.polyswarm.network/balances/2e03565b735e2343f7f0501a7772a42b1c0e8893/staking/total
{"result":"10000000000000000000000000","status":"OK"}
```

Think transaction response isn't being handled by arbiter cuckoo (step 2 above) https://github.com/polyswarm/arbiter-cuckoo/blob/b498c2cb1d23c18fe15779762c47bb148287ec70/arbiter/polyswarm_api.py#L144

Will update ticket when we track this down.

**Comment by mjkoo** [comment]
Closed by https://github.com/polyswarm/arbiter-cuckoo/pull/2
