### ISSUE TITLE
We're doing a lot before `main()`

### ISSUE THREAD

**Issue by telwell** [polyswarm/polyswarmd#71]
**Is your feature request related to a problem? Please describe.**
One of my tickets involved setting up the ability to output logs in JSON format via a command line arg. Presently, we use the `@click` ([more info](https://click.palletsprojects.com/en/7.x/)) decorator on `main()` in `__main__.py` to parse CL args. Initially, I tried to add my JSON format CL arg here, but further inspection revealed that there were lots of log outputs _before_ we even got into `main()`.

I believe this is because in `__main__.py` we import `from polyswarmd import app` which prompts `__init__.py` to be run. And there is a lot of heavy lifting in `__init__.py`. Notable functions include `init_config()` which is imported from `config.py` and runs a lot of configuration logic. 

**Describe the solution you'd like**
I believe we should move the business logic of init_config and init_logging into `__main__`. AFIK we only need to instantiate the flask app in `__init__.py`, most everything else can move to main. When we do, we should move JSON logging away from environment variable and to command line argument.

**Describe alternatives you've considered**
The alternative is to let sleeping dogs lie and not worry about it. I think this could cause frustration down the road, though, if we want to add more CL arguments to polyswarmd.

**Comment by myhndl** [comment]
The reason for this basically boils down to: Flask does gross things, resulting in odd requirements like logic before main() and import order mattering. 

In other words, this appears to be a limitation imposed on us that we'll just have to work with. We won't move logic into `main()`. That being said, the user should be able to specify `LOG_FORMAT` via the CLI, so please file a separate ticket to track this @telwell .

See more discussion on Flask being gross here: https://polyswarminternal.slack.com/archives/C9R80LXCZ/p1538949069000100
