### ISSUE TITLE
Update Docker instructions in README

### ISSUE THREAD

**Issue by telwell** [polyswarm/polyswarmd#73]
**Describe the bug**
In `README.rst` under docker we have the instructions:
```
...
1) Run with ``docker-compose -f docker/docker-compose.yml up``
```

We should update the readme to conform more closely with our other documentation ([here](https://docs.polyswarm.io/Level-0-scratch-to-eicar/)). 

**To Reproduce**
N/A

**Comment by myhndl** [comment]
This docker-compose file was abandoned a while ago. Please remove and point people to docs.polyswarm.io in README

**Comment by myhndl** [comment]
done
