### ISSUE TITLE
Logging logic will break `--log` argument

### ISSUE THREAD

**Issue by telwell** [polyswarm/polyswarmd#77]
_Related to [[76]](https://github.com/polyswarm/polyswarmd/issues/76)_

**Describe the bug**
I added `init_logging()` to the `__init__.py`. But, the `--log` flag isn't gotten from click until `main()`. Therefore, any argument passed to `--log` will be moot. This defaults to `INFO` level logging for now, but this cannot be changed the way it's written now. Whoever tackles related #76 above should also tackle this bug.

**Expected behavior**
Passing in a CL argument to `--log` should set the default log level.

**Comment by myhndl** [comment]
If the log format is an env var, the log level should be as well for now.

**Comment by myhndl** [comment]
is this a dupe of this https://github.com/polyswarm/polyswarmd/issues/76

**Comment by myhndl** [comment]
When we get back to this, `--log` is an ambiguous name. Let's do `log-level`
