### ISSUE TITLE
polyswarmd Has no Chill Waiting for Consul

### ISSUE THREAD

**Issue by myhndl** [polyswarm/polyswarmd#79]
**Describe the bug**
It says it's waiting and it doesn't

**To Reproduce**
run it

**Expected behavior**
it waits

**Comment by myhndl** [comment]
https://github.com/polyswarm/polyswarmd/blob/fff98e25a4907e5630fc1288254f9f2c676495e6/src/polyswarmd/config.py#L55

**Comment by mjkoo** [comment]
This was resolved in #80 afaict, closing
